<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.1</Version>
    <Authors>lspx-1</Authors>
    <Product>Bastion Antivirus</Product>
    <Copyright>Copyright (c) 2026 lspx-1</Copyright>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SatelliteResourceLanguages>en;de</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
